"""add_firebase_uid_to_users

Revision ID: b1804dc1b57c
Revises: 0002_create_wallets_and_transactions
Create Date: 2026-09-08 11:43:23.654826

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b1804dc1b57c'
down_revision: Union[str, None] = '0002_create_wallets_and_transactions'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users') as batch_op:
        batch_op.add_column(sa.Column('firebase_uid', sa.String(length=128), nullable=True))
        batch_op.alter_column('password_hash',
                   existing_type=sa.TEXT(),
                   nullable=True)
        batch_op.create_index(batch_op.f('ix_users_firebase_uid'), ['firebase_uid'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users') as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_firebase_uid'))
        batch_op.alter_column('password_hash',
                   existing_type=sa.TEXT(),
                   nullable=False)
        batch_op.drop_column('firebase_uid')
    # ### end Alembic commands ###
